server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  main:
    allow-circular-references: true
#  mvc:
#    pathmath:
#      matching-strategy: ant_path_matcher

  profiles:
    #    active: release
    active: dev

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
